version: "3"

services:
  database:
    image: bitnami/postgresql:14
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  opensearch:
    image: elasticsearch:7.17.16
    container_name: opensearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
  cache:
    image: eqalpha/keydb
    container_name: cache
    restart: unless-stopped
    command:
      - keydb-server
      - --server-threads 2
      - --requirepass dev
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
  pgsync:
    image: ifelsedotone/pgsync:latest
    container_name: pgsync
    restart: always
    environment:
      - PG_HOST=database
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_SSLMODE=disable
      - ELASTICSEARCH_HOST=opensearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_AUTH=dev
    volumes:
      - "./pgsync.json:/etc/schema.json"
    depends_on:
      cache:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      database:
        condition: service_healthy
